### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by heatherpriceonline** [Halleck45/BDDWizard#7]
I ran the wget and the php commands, but I don't understand how this is supposed to generate reports. 

Was I supposed to download the .zip and extract it in a specific place?

What do I need to do to get this running?

Thanks.

**Comment by Halleck45** [comment]
You should also run the second line:

``` bash
wget ...
php bdd-wizard.phar --features=/path/of/features --reports=/path/of/junit-format/results
```

This command will run a PHP webserver.
